# Generated by Django 4.0.3 on 2022-03-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_blog_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
