# Generated by Django 4.0.3 on 2022-03-23 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
