# Generated by Django 4.0.3 on 2022-03-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
